import Rigid.AffinoidSpectrum.GeneratedCoverReduction

set_option linter.style.header false

/-!
# Generated rational covers restricted to rational subdomains

After restriction to a rational subdomain and rebasing, a generated rational
cover is the cover generated by the images of the same finite family.  This
gives the universal form of generated-cover acyclicity needed in Čech
comparison arguments.
-/

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

namespace AffinoidRationalSubdomain.Cover

private noncomputable abbrev mappedGeneratedFamily {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A) : Fin r → W.Sections :=
  fun i ↦ RationalLocalization.baseMap K A W.n W.g W.f (q i)

private theorem mappedGeneratedFamily_span_top {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) :
    Ideal.span (Set.range (mappedGeneratedFamily K A W q)) = ⊤ := by
  classical
  have hmem : (1 : A) ∈ Ideal.span (Set.range q) := by
    rw [hq]
    exact Submodule.mem_top
  obtain ⟨a, ha⟩ := Ideal.mem_span_range_iff_exists_fun.mp hmem
  apply (Ideal.eq_top_iff_one _).mpr
  rw [Ideal.mem_span_range_iff_exists_fun]
  refine ⟨fun i ↦ RationalLocalization.baseMap K A W.n W.g W.f (a i), ?_⟩
  simp only [mappedGeneratedFamily]
  simp_rw [← map_mul]
  rw [← map_sum, ha, map_one]

private noncomputable abbrev rebasedRestrictedGenerated {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) :
    Cover K W.Sections (whole K W.Sections) :=
  ((generated K A q hq).restrictTo K A W (by
    simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A

private noncomputable abbrev mappedGenerated {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) :
    Cover K W.Sections (whole K W.Sections) :=
  generated K W.Sections (mappedGeneratedFamily K A W q)
    (mappedGeneratedFamily_span_top K A W q hq)

private theorem rebase_restrictTo_generated_domain_carrier_eq {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (i : Fin r) :
    ((rebasedRestrictedGenerated K A W q hq).domain i).carrier =
      ((mappedGenerated K A W q hq).domain i).carrier := by
  ext y
  rw [mem_rebase_carrier_iff]
  change
    ambientPoint K A W y ∈ (inter K A W (generatedDomain K A q hq i)).carrier ↔
      y ∈ (generatedDomain K W.Sections
        (mappedGeneratedFamily K A W q)
        (mappedGeneratedFamily_span_top K A W q hq) i).carrier
  rw [carrier_inter, Set.mem_inter_iff, mem_generatedDomain_carrier,
    mem_generatedDomain_carrier]
  simp_rw [← ambientPoint_apply K A W]
  constructor
  · exact And.right
  · exact fun h ↦ ⟨ambientPoint_mem_carrier K A W y, h⟩

private noncomputable def mappedGeneratedRefinementRebasedRestricted {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) :
    Refinement K W.Sections
      (mappedGenerated K A W q hq)
      (rebasedRestrictedGenerated K A W q hq) where
  index i := i
  subset i := (rebase_restrictTo_generated_domain_carrier_eq K A W q hq i).ge

private noncomputable def rebasedRestrictedRefinementMappedGenerated {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) :
    Refinement K W.Sections
      (rebasedRestrictedGenerated K A W q hq)
      (mappedGenerated K A W q hq) where
  index i := i
  subset i := (rebase_restrictTo_generated_domain_carrier_eq K A W q hq i).le

/-- A cover generated by a finite unit-ideal family remains acyclic after
restriction to every rational subdomain. -/
theorem restrictTo_generated_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) {r : ℕ}
    (W : AffinoidRationalSubdomain K A) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r)) :
    (((generated K A q hq).restrictTo K A W (by
      simpa only [carrier_whole] using Set.subset_univ W.carrier)
        ).normalizedCechComplex K A hA).Acyclic := by
  rw [normalizedCechComplex_acyclic_iff_rebase K A hA]
  exact
    (normalizedCechComplex_acyclic_iff_of_mutual_refinement K W.Sections
      (isAffinoidAlgebra_sections K A hA W)
      (rebasedRestrictedGenerated K A W q hq)
      (mappedGenerated K A W q hq)
      (mappedGeneratedRefinementRebasedRestricted K A W q hq)
      (rebasedRestrictedRefinementMappedGenerated K A W q hq)).2
        (generated_normalizedCechComplex_acyclic K W.Sections
          (isAffinoidAlgebra_sections K A hA W)
          (mappedGeneratedFamily K A W q)
          (mappedGeneratedFamily_span_top K A W q hq) hr)

end AffinoidRationalSubdomain.Cover

end Rigid
