import Rigid.AffinoidSpectrum.UnitGeneratedCover

set_option linter.style.header false

/-!
# Reduction of generated rational covers to unit-generated covers

This file formalizes BGR 8.2.2, Lemma 3.  A common scalar makes a finite
unit-ideal family pointwise large somewhere.  On every chart of the Laurent
cover generated by the scaled family, the restricted rational cover is
equivalent to one generated by units.
-/

open scoped BigOperators

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

namespace AffinoidRationalSubdomain.Cover

private def scaledFamily {r : ℕ} (c : K) (q : Fin r → A) : Fin r → A :=
  fun i ↦ algebraMap K A c * q i

@[simp]
private theorem apply_scaledFamily {r : ℕ} (c : K) (q : Fin r → A)
    (i : Fin r) (x : BerkovichSpectrumOver K A) :
    x (scaledFamily K A c q i) = ‖c‖ * x (q i) := by
  simp [scaledFamily]

private theorem scaledFamily_le_scaledFamily_iff {r : ℕ} {c : K}
    (hc : 0 < ‖c‖) (q : Fin r → A) (i j : Fin r)
    (x : BerkovichSpectrumOver K A) :
    x (scaledFamily K A c q i) ≤ x (scaledFamily K A c q j) ↔
      x (q i) ≤ x (q j) := by
  simp only [apply_scaledFamily]
  exact mul_le_mul_iff_right₀ hc

/-- A finite family spanning the unit ideal can be scaled so that at every
Berkovich point at least one member has value strictly greater than one. -/
private theorem exists_scalingConstant {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r)) :
    ∃ c : K, 0 < ‖c‖ ∧
      ∀ x : BerkovichSpectrumOver K A,
        ∃ i : Fin r, 1 < x (scaledFamily K A c q i) := by
  have hmem : (1 : A) ∈ Ideal.span (Set.range q) := by
    rw [hq]
    exact Submodule.mem_top
  obtain ⟨a, ha⟩ :=
    Ideal.mem_span_range_iff_exists_fun.mp hmem
  letI : Nonempty (Fin r) := hr
  obtain ⟨imax, himax⟩ := Finite.exists_max (fun i : Fin r ↦ ‖a i‖)
  obtain ⟨c, hc⟩ := NormedField.exists_lt_norm K ‖a imax‖
  have hcpos : 0 < ‖c‖ :=
    (norm_nonneg (a imax)).trans_lt hc
  refine ⟨c, hcpos, fun x ↦ ?_⟩
  by_contra hlarge
  push Not at hlarge
  have hterm (i : Fin r) : x (a i * q i) < 1 := by
    by_cases hqi : x (q i) = 0
    · rw [BerkovichSpectrumOver.map_mul, hqi, mul_zero]
      exact zero_lt_one
    · have hqipos : 0 < x (q i) :=
        lt_of_le_of_ne (BerkovichSpectrumOver.nonneg K A x (q i)) (Ne.symm hqi)
      calc
        x (a i * q i) = x (a i) * x (q i) := by
          rw [BerkovichSpectrumOver.map_mul]
        _ ≤ ‖a i‖ * x (q i) :=
          mul_le_mul_of_nonneg_right (BerkovichSpectrumOver.le_norm K A x (a i))
            hqipos.le
        _ < ‖c‖ * x (q i) :=
          mul_lt_mul_of_pos_right ((himax i).trans_lt hc) hqipos
        _ = x (scaledFamily K A c q i) := by
          rw [apply_scaledFamily]
        _ ≤ 1 := hlarge i
  have hsum : x (∑ i, a i * q i) < 1 := by
    classical
    let s : Finset (Fin r) := Finset.univ
    change x (∑ i ∈ s, a i * q i) < 1
    induction s using Finset.induction_on with
    | empty => simp
    | @insert i s hi ih =>
        rw [Finset.sum_insert hi]
        exact (BerkovichSpectrum.map_add_le_max x.toBerkovichSpectrum
          (a i * q i) (∑ j ∈ s, a j * q j)).trans_lt
            (max_lt (hterm i) ih)
  rw [ha, BerkovichSpectrumOver.map_one] at hsum
  exact (lt_irrefl 1) hsum

private noncomputable def scaledFamilyList {r : ℕ} (c : K) (q : Fin r → A) :
    List A :=
  List.ofFn (scaledFamily K A c q)

private theorem scaledFamily_mem_list {r : ℕ} (c : K) (q : Fin r → A)
    (i : Fin r) :
    scaledFamily K A c q i ∈ scaledFamilyList K A c q := by
  rw [scaledFamilyList, List.mem_ofFn']
  exact ⟨i, rfl⟩

private noncomputable def scaledLaurentCover {r : ℕ} (c : K) (q : Fin r → A) :
    Cover K A (whole K A) :=
  laurentProduct K A 1 (scaledFamilyList K A c q)

private def IsGESign {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r) : Prop :=
  ∀ x ∈ ((scaledLaurentCover K A c q).domain k).carrier,
    1 ≤ x (scaledFamily K A c q i)

private def IsLESign {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r) : Prop :=
  ∀ x ∈ ((scaledLaurentCover K A c q).domain k).carrier,
    x (scaledFamily K A c q i) ≤ 1

private theorem le_or_ge_sign {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r) :
    IsLESign K A c q k i ∨ IsGESign K A c q k i :=
  laurentProduct_domain_sign_of_mem K A 1
    (scaledFamilyList K A c q) (scaledFamily K A c q i)
    (Or.inr (scaledFamily_mem_list K A c q i)) k

private theorem le_sign_of_not_ge {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (hi : ¬ IsGESign K A c q k i) :
    IsLESign K A c q k i :=
  (le_or_ge_sign K A c q k i).resolve_right hi

private theorem exists_ge_sign {r : ℕ} (c : K) (q : Fin r → A)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) :
    ∃ i : Fin r, IsGESign K A c q k i := by
  by_cases hchart :
      ((scaledLaurentCover K A c q).domain k).carrier.Nonempty
  · obtain ⟨x, hx⟩ := hchart
    obtain ⟨i, hi⟩ := hlarge x
    refine ⟨i, ?_⟩
    rcases le_or_ge_sign K A c q k i with hle | hge
    · exact False.elim (not_lt_of_ge (hle x hx) hi)
    · exact hge
  · let i : Fin r := Classical.choice hr
    exact ⟨i, fun x hx ↦ False.elim (hchart ⟨x, hx⟩)⟩

private noncomputable abbrev chartBaseMap {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) :
    ContinuousAlgHom K A ((scaledLaurentCover K A c q).domain k).Sections :=
  RationalLocalization.baseMap K A
    ((scaledLaurentCover K A c q).domain k).n
    ((scaledLaurentCover K A c q).domain k).g
    ((scaledLaurentCover K A c q).domain k).f

/-- Replace the scaled generators with value at most one on a Laurent chart
by `1`.  The remaining generators become units on the chart. -/
private noncomputable def localUnitFamily {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) :
    Fin r → ((scaledLaurentCover K A c q).domain k).Sections := by
  classical
  exact fun i ↦ if IsGESign K A c q k i then
      chartBaseMap K A c q k (scaledFamily K A c q i)
    else 1

private theorem localUnitFamily_isUnit {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r) :
    IsUnit (localUnitFamily K A c q k i) := by
  by_cases hi : IsGESign K A c q k i
  · rw [localUnitFamily, if_pos hi]
    rw [BerkovichSpectrumOver.isUnit_iff_forall_apply_ne_zero K
      ((scaledLaurentCover K A c q).domain k).Sections]
    intro y
    have hval := hi (ambientPoint K A
      ((scaledLaurentCover K A c q).domain k) y)
      (ambientPoint_mem_carrier K A
        ((scaledLaurentCover K A c q).domain k) y)
    rw [ambientPoint_apply K A ((scaledLaurentCover K A c q).domain k)] at hval
    exact ne_of_gt (zero_lt_one.trans_le hval)
  · rw [localUnitFamily, if_neg hi]
    exact isUnit_one

private theorem localUnitFamily_span_top {r : ℕ} {c : K} (hc : c ≠ 0)
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m) :
    Ideal.span (Set.range (localUnitFamily K A c q k)) = ⊤ := by
  classical
  by_cases hall : ∀ i, IsGESign K A c q k i
  · have hmem : (1 : A) ∈ Ideal.span (Set.range q) := by
      rw [hq]
      exact Submodule.mem_top
    obtain ⟨a, ha⟩ :=
      Ideal.mem_span_range_iff_exists_fun.mp hmem
    apply (Ideal.eq_top_iff_one _).mpr
    rw [Ideal.mem_span_range_iff_exists_fun]
    refine ⟨fun i ↦ chartBaseMap K A c q k
      (algebraMap K A c⁻¹ * a i), ?_⟩
    simp only [localUnitFamily]
    simp_rw [if_pos (hall _)]
    simp_rw [← map_mul]
    rw [← map_sum]
    have hsum :
        ∑ i, (algebraMap K A c⁻¹ * a i) * scaledFamily K A c q i = 1 := by
      calc
        ∑ i, (algebraMap K A c⁻¹ * a i) * scaledFamily K A c q i =
            ∑ i, a i * q i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [scaledFamily]
          calc
            (algebraMap K A c⁻¹ * a i) * (algebraMap K A c * q i) =
                (algebraMap K A c⁻¹ * algebraMap K A c) * (a i * q i) := by
              ring
            _ = a i * q i := by
              rw [← map_mul, inv_mul_cancel₀ hc, map_one, one_mul]
        _ = 1 := ha
    rw [hsum, map_one]
  · obtain ⟨i, hi⟩ := not_forall.mp hall
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨i, ?_⟩
    simp [localUnitFamily, hi]

private noncomputable abbrev rebasedRestrictedGeneratedCover {r : ℕ}
    (c : K) (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m) :
    Cover K ((scaledLaurentCover K A c q).domain k).Sections
      (whole K ((scaledLaurentCover K A c q).domain k).Sections) :=
  ((generated K A q hq).restrictTo K A
    ((scaledLaurentCover K A c q).domain k) (by
      simpa only [carrier_whole] using
        Set.subset_univ ((scaledLaurentCover K A c q).domain k).carrier)).rebase K A

private noncomputable abbrev localGeneratedCover {r : ℕ} {c : K} (hc : c ≠ 0)
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m) :
    Cover K ((scaledLaurentCover K A c q).domain k).Sections
      (whole K ((scaledLaurentCover K A c q).domain k).Sections) :=
  generated K ((scaledLaurentCover K A c q).domain k).Sections
    (localUnitFamily K A c q k)
    (localUnitFamily_span_top K A hc q hq k)

private theorem mem_rebasedRestrictedGeneratedCover_domain_iff {r : ℕ}
    (c : K) (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (y : BerkovichSpectrumOver K
      ((scaledLaurentCover K A c q).domain k).Sections) :
    y ∈ ((rebasedRestrictedGeneratedCover K A c q hq k).domain i).carrier ↔
      ∀ j, ambientPoint K A ((scaledLaurentCover K A c q).domain k) y (q j) ≤
        ambientPoint K A ((scaledLaurentCover K A c q).domain k) y (q i) := by
  rw [mem_rebase_carrier_iff, carrier_inter, Set.mem_inter_iff]
  change
    ambientPoint K A ((scaledLaurentCover K A c q).domain k) y ∈
        ((scaledLaurentCover K A c q).domain k).carrier ∧
      ambientPoint K A ((scaledLaurentCover K A c q).domain k) y ∈
        (generatedDomain K A q hq i).carrier ↔ _
  rw [mem_generatedDomain_carrier]
  constructor
  · exact fun h ↦ h.2
  · exact fun h ↦
      ⟨ambientPoint_mem_carrier K A
        ((scaledLaurentCover K A c q).domain k) y, h⟩

private theorem chartBaseMap_scaled_le_iff {r : ℕ} {c : K}
    (hc : 0 < ‖c‖) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i j : Fin r)
    (y : BerkovichSpectrumOver K
      ((scaledLaurentCover K A c q).domain k).Sections) :
    y (chartBaseMap K A c q k (scaledFamily K A c q i)) ≤
        y (chartBaseMap K A c q k (scaledFamily K A c q j)) ↔
      ambientPoint K A ((scaledLaurentCover K A c q).domain k) y (q i) ≤
        ambientPoint K A ((scaledLaurentCover K A c q).domain k) y (q j) := by
  rw [← ambientPoint_apply K A ((scaledLaurentCover K A c q).domain k),
    ← ambientPoint_apply K A ((scaledLaurentCover K A c q).domain k)]
  exact scaledFamily_le_scaledFamily_iff K A hc q i j _

private theorem ge_sign_value {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (hi : IsGESign K A c q k i)
    (y : BerkovichSpectrumOver K
      ((scaledLaurentCover K A c q).domain k).Sections) :
    1 ≤ y (chartBaseMap K A c q k (scaledFamily K A c q i)) := by
  rw [← ambientPoint_apply K A ((scaledLaurentCover K A c q).domain k)]
  exact hi _ (ambientPoint_mem_carrier K A
    ((scaledLaurentCover K A c q).domain k) y)

private theorem le_sign_value {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (hi : IsLESign K A c q k i)
    (y : BerkovichSpectrumOver K
      ((scaledLaurentCover K A c q).domain k).Sections) :
    y (chartBaseMap K A c q k (scaledFamily K A c q i)) ≤ 1 := by
  rw [← ambientPoint_apply K A ((scaledLaurentCover K A c q).domain k)]
  exact hi _ (ambientPoint_mem_carrier K A
    ((scaledLaurentCover K A c q).domain k) y)

private noncomputable def geOwner {r : ℕ} (c : K) (q : Fin r → A)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) : Fin r :=
  Classical.choose (exists_ge_sign K A c q hr hlarge k)

private theorem geOwner_spec {r : ℕ} (c : K) (q : Fin r → A)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) :
    IsGESign K A c q k (geOwner K A c q hr hlarge k) :=
  Classical.choose_spec (exists_ge_sign K A c q hr hlarge k)

private noncomputable def geIndex {r : ℕ} (c : K) (q : Fin r → A)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r) : Fin r := by
  classical
  exact if IsGESign K A c q k i then i else geOwner K A c q hr hlarge k

private noncomputable def rebasedRestrictedGeneratedRefinementLocal {r : ℕ}
    {c : K} (hc : 0 < ‖c‖) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) :
    Refinement K ((scaledLaurentCover K A c q).domain k).Sections
      (rebasedRestrictedGeneratedCover K A c q hq k)
      (localGeneratedCover K A (norm_pos_iff.mp hc) q hq k) where
  index i := geIndex K A c q hr hlarge k i
  subset i y hy := by
    classical
    change Fin r at i
    have horig :=
      (mem_rebasedRestrictedGeneratedCover_domain_iff K A c q hq k i y).1 hy
    change y ∈ (generatedDomain K
      ((scaledLaurentCover K A c q).domain k).Sections
      (localUnitFamily K A c q k)
      (localUnitFamily_span_top K A (norm_pos_iff.mp hc) q hq k)
      (geIndex K A c q hr hlarge k i)).carrier
    rw [mem_generatedDomain_carrier]
    intro j
    by_cases hi : IsGESign K A c q k i
    · simp only [geIndex, hi, if_pos]
      by_cases hj : IsGESign K A c q k j
      · rw [localUnitFamily, if_pos hj, localUnitFamily, if_pos hi]
        exact
          (chartBaseMap_scaled_le_iff K A hc q k j i y).2 (horig j)
      · rw [localUnitFamily, if_neg hj, localUnitFamily, if_pos hi,
          BerkovichSpectrumOver.map_one]
        exact ge_sign_value K A c q k i hi y
    · let owner := geOwner K A c q hr hlarge k
      have hindex :
          geIndex K A c q hr hlarge k i = owner := by
        simp [geIndex, hi, owner]
      rw [hindex]
      have howner : IsGESign K A c q k owner :=
        geOwner_spec K A c q hr hlarge k
      by_cases hj : IsGESign K A c q k j
      · rw [localUnitFamily, if_pos hj, localUnitFamily, if_pos howner]
        exact ((chartBaseMap_scaled_le_iff K A hc q k j i y).2
          (horig j)).trans
            ((le_sign_value K A c q k i
              (le_sign_of_not_ge K A c q k i hi) y).trans
                (ge_sign_value K A c q k owner howner y))
      · rw [localUnitFamily, if_neg hj, localUnitFamily, if_pos howner,
          BerkovichSpectrumOver.map_one]
        exact ge_sign_value K A c q k owner howner y

private noncomputable def localRefinementRebasedRestrictedGenerated {r : ℕ}
    {c : K} (hc : 0 < ‖c‖) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) :
    Refinement K ((scaledLaurentCover K A c q).domain k).Sections
      (localGeneratedCover K A (norm_pos_iff.mp hc) q hq k)
      (rebasedRestrictedGeneratedCover K A c q hq k) where
  index i := geIndex K A c q hr hlarge k i
  subset i y hy := by
    classical
    change Fin r at i
    have hlocal :
        ∀ j, y (localUnitFamily K A c q k j) ≤
          y (localUnitFamily K A c q k i) := by
      change y ∈ (generatedDomain K
        ((scaledLaurentCover K A c q).domain k).Sections
        (localUnitFamily K A c q k)
        (localUnitFamily_span_top K A (norm_pos_iff.mp hc) q hq k) i).carrier at hy
      exact (mem_generatedDomain_carrier K
        ((scaledLaurentCover K A c q).domain k).Sections
        (localUnitFamily K A c q k)
        (localUnitFamily_span_top K A (norm_pos_iff.mp hc) q hq k) i y).1 hy
    apply
      (mem_rebasedRestrictedGeneratedCover_domain_iff K A c q hq k
        (geIndex K A c q hr hlarge k i) y).2
    intro j
    by_cases hi : IsGESign K A c q k i
    · simp only [geIndex, hi, if_pos]
      apply (chartBaseMap_scaled_le_iff K A hc q k j i y).1
      by_cases hj : IsGESign K A c q k j
      · simpa only [localUnitFamily, if_pos hj, if_pos hi] using hlocal j
      · exact (le_sign_value K A c q k j
          (le_sign_of_not_ge K A c q k j hj) y).trans
            (ge_sign_value K A c q k i hi y)
    · let owner := geOwner K A c q hr hlarge k
      have hindex :
          geIndex K A c q hr hlarge k i = owner := by
        simp [geIndex, hi, owner]
      rw [hindex]
      have howner : IsGESign K A c q k owner :=
        geOwner_spec K A c q hr hlarge k
      apply (chartBaseMap_scaled_le_iff K A hc q k j owner y).1
      by_cases hj : IsGESign K A c q k j
      · have hjone :
            y (chartBaseMap K A c q k (scaledFamily K A c q j)) ≤ 1 := by
          simpa only [localUnitFamily, if_pos hj, if_neg hi,
            BerkovichSpectrumOver.map_one] using hlocal j
        exact hjone.trans (ge_sign_value K A c q k owner howner y)
      · exact (le_sign_value K A c q k j
          (le_sign_of_not_ge K A c q k j hj) y).trans
            (ge_sign_value K A c q k owner howner y)

/-- On a scaled Laurent chart, the restriction of a generated rational cover
is equivalent to a cover generated by units. -/
private theorem restrictTo_generated_chart_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) {r : ℕ} {c : K} (hc : 0 < ‖c‖)
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m) :
    (((generated K A q hq).restrictTo K A
      ((scaledLaurentCover K A c q).domain k)
      ((scaledLaurentCover K A c q).subset k)).normalizedCechComplex K A hA).Acyclic := by
  rw [normalizedCechComplex_acyclic_iff_rebase K A hA]
  exact
    (normalizedCechComplex_acyclic_iff_of_mutual_refinement K
      ((scaledLaurentCover K A c q).domain k).Sections
      (isAffinoidAlgebra_sections K A hA
        ((scaledLaurentCover K A c q).domain k))
      (rebasedRestrictedGeneratedCover K A c q hq k)
      (localGeneratedCover K A (norm_pos_iff.mp hc) q hq k)
      (localRefinementRebasedRestrictedGenerated K A hc q hq hr hlarge k)
      (rebasedRestrictedGeneratedRefinementLocal K A hc q hq hr hlarge k)).2
        (unitGenerated_normalizedCechComplex_acyclic K
          ((scaledLaurentCover K A c q).domain k).Sections
          (isAffinoidAlgebra_sections K A hA
            ((scaledLaurentCover K A c q).domain k))
          (localUnitFamily K A c q k)
          (localUnitFamily_span_top K A (norm_pos_iff.mp hc) q hq k)
          hr (localUnitFamily_isUnit K A c q k))

private noncomputable abbrev subdomainBaseMap
    (W : AffinoidRationalSubdomain K A) :
    ContinuousAlgHom K A W.Sections :=
  RationalLocalization.baseMap K A W.n W.g W.f

/-- The unit family belonging to a scaled Laurent chart, pulled all the way
back to a rational subdomain of that chart. -/
private noncomputable def localUnitFamilyOn {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A) : Fin r → W.Sections := by
  classical
  exact fun i ↦ if IsGESign K A c q k i then
      subdomainBaseMap K A W (scaledFamily K A c q i)
    else 1

private theorem localUnitFamilyOn_isUnit {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier)
    (i : Fin r) :
    IsUnit (localUnitFamilyOn K A c q k W i) := by
  by_cases hi : IsGESign K A c q k i
  · rw [localUnitFamilyOn, if_pos hi]
    rw [BerkovichSpectrumOver.isUnit_iff_forall_apply_ne_zero K W.Sections]
    intro y
    have hval := hi (ambientPoint K A W y)
      (hW (ambientPoint_mem_carrier K A W y))
    rw [ambientPoint_apply K A W] at hval
    exact ne_of_gt (zero_lt_one.trans_le hval)
  · rw [localUnitFamilyOn, if_neg hi]
    exact isUnit_one

private theorem localUnitFamilyOn_span_top {r : ℕ} {c : K} (hc : c ≠ 0)
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A) :
    Ideal.span (Set.range (localUnitFamilyOn K A c q k W)) = ⊤ := by
  classical
  by_cases hall : ∀ i, IsGESign K A c q k i
  · have hmem : (1 : A) ∈ Ideal.span (Set.range q) := by
      rw [hq]
      exact Submodule.mem_top
    obtain ⟨a, ha⟩ :=
      Ideal.mem_span_range_iff_exists_fun.mp hmem
    apply (Ideal.eq_top_iff_one _).mpr
    rw [Ideal.mem_span_range_iff_exists_fun]
    refine ⟨fun i ↦ subdomainBaseMap K A W
      (algebraMap K A c⁻¹ * a i), ?_⟩
    simp only [localUnitFamilyOn]
    simp_rw [if_pos (hall _)]
    simp_rw [← map_mul]
    rw [← map_sum]
    have hsum :
        ∑ i, (algebraMap K A c⁻¹ * a i) * scaledFamily K A c q i = 1 := by
      calc
        ∑ i, (algebraMap K A c⁻¹ * a i) * scaledFamily K A c q i =
            ∑ i, a i * q i := by
          apply Finset.sum_congr rfl
          intro i _
          rw [scaledFamily]
          calc
            (algebraMap K A c⁻¹ * a i) * (algebraMap K A c * q i) =
                (algebraMap K A c⁻¹ * algebraMap K A c) * (a i * q i) := by
              ring
            _ = a i * q i := by
              rw [← map_mul, inv_mul_cancel₀ hc, map_one, one_mul]
        _ = 1 := ha
    rw [hsum, map_one]
  · obtain ⟨i, hi⟩ := not_forall.mp hall
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨i, ?_⟩
    simp [localUnitFamilyOn, hi]

private noncomputable abbrev rebasedRestrictedGeneratedCoverOn {r : ℕ}
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (W : AffinoidRationalSubdomain K A) :
    Cover K W.Sections (whole K W.Sections) :=
  ((generated K A q hq).restrictTo K A W (by
    simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A

private noncomputable abbrev localGeneratedCoverOn {r : ℕ} {c : K}
    (hc : c ≠ 0) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤)
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A) :
    Cover K W.Sections (whole K W.Sections) :=
  generated K W.Sections (localUnitFamilyOn K A c q k W)
    (localUnitFamilyOn_span_top K A hc q hq k W)

private theorem mem_rebasedRestrictedGeneratedCoverOn_domain_iff {r : ℕ}
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (W : AffinoidRationalSubdomain K A) (i : Fin r)
    (y : BerkovichSpectrumOver K W.Sections) :
    y ∈ ((rebasedRestrictedGeneratedCoverOn K A q hq W).domain i).carrier ↔
      ∀ j, ambientPoint K A W y (q j) ≤ ambientPoint K A W y (q i) := by
  rw [mem_rebase_carrier_iff, carrier_inter, Set.mem_inter_iff]
  change
    ambientPoint K A W y ∈ W.carrier ∧
      ambientPoint K A W y ∈ (generatedDomain K A q hq i).carrier ↔ _
  rw [mem_generatedDomain_carrier]
  constructor
  · exact fun h ↦ h.2
  · exact fun h ↦ ⟨ambientPoint_mem_carrier K A W y, h⟩

private theorem subdomainBaseMap_scaled_le_iff {r : ℕ} {c : K}
    (hc : 0 < ‖c‖) (q : Fin r → A)
    (W : AffinoidRationalSubdomain K A) (i j : Fin r)
    (y : BerkovichSpectrumOver K W.Sections) :
    y (subdomainBaseMap K A W (scaledFamily K A c q i)) ≤
        y (subdomainBaseMap K A W (scaledFamily K A c q j)) ↔
      ambientPoint K A W y (q i) ≤ ambientPoint K A W y (q j) := by
  rw [← ambientPoint_apply K A W, ← ambientPoint_apply K A W]
  exact scaledFamily_le_scaledFamily_iff K A hc q i j _

private theorem ge_sign_value_on {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (hi : IsGESign K A c q k i)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier)
    (y : BerkovichSpectrumOver K W.Sections) :
    1 ≤ y (subdomainBaseMap K A W (scaledFamily K A c q i)) := by
  rw [← ambientPoint_apply K A W]
  exact hi _ (hW (ambientPoint_mem_carrier K A W y))

private theorem le_sign_value_on {r : ℕ} (c : K) (q : Fin r → A)
    (k : Fin (scaledLaurentCover K A c q).m) (i : Fin r)
    (hi : IsLESign K A c q k i)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier)
    (y : BerkovichSpectrumOver K W.Sections) :
    y (subdomainBaseMap K A W (scaledFamily K A c q i)) ≤ 1 := by
  rw [← ambientPoint_apply K A W]
  exact hi _ (hW (ambientPoint_mem_carrier K A W y))

private noncomputable def rebasedRestrictedGeneratedOnRefinementLocal {r : ℕ}
    {c : K} (hc : 0 < ‖c‖) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier) :
    Refinement K W.Sections
      (rebasedRestrictedGeneratedCoverOn K A q hq W)
      (localGeneratedCoverOn K A (norm_pos_iff.mp hc) q hq k W) where
  index i := geIndex K A c q hr hlarge k i
  subset i y hy := by
    classical
    change Fin r at i
    have horig :=
      (mem_rebasedRestrictedGeneratedCoverOn_domain_iff K A q hq W i y).1 hy
    change y ∈ (generatedDomain K W.Sections
      (localUnitFamilyOn K A c q k W)
      (localUnitFamilyOn_span_top K A (norm_pos_iff.mp hc) q hq k W)
      (geIndex K A c q hr hlarge k i)).carrier
    rw [mem_generatedDomain_carrier]
    intro j
    by_cases hi : IsGESign K A c q k i
    · simp only [geIndex, hi, if_pos]
      by_cases hj : IsGESign K A c q k j
      · rw [localUnitFamilyOn, if_pos hj, localUnitFamilyOn, if_pos hi]
        exact (subdomainBaseMap_scaled_le_iff K A hc q W j i y).2 (horig j)
      · rw [localUnitFamilyOn, if_neg hj, localUnitFamilyOn, if_pos hi,
          BerkovichSpectrumOver.map_one]
        exact ge_sign_value_on K A c q k i hi W hW y
    · let owner := geOwner K A c q hr hlarge k
      have hindex : geIndex K A c q hr hlarge k i = owner := by
        simp [geIndex, hi, owner]
      rw [hindex]
      have howner : IsGESign K A c q k owner :=
        geOwner_spec K A c q hr hlarge k
      by_cases hj : IsGESign K A c q k j
      · rw [localUnitFamilyOn, if_pos hj, localUnitFamilyOn, if_pos howner]
        exact ((subdomainBaseMap_scaled_le_iff K A hc q W j i y).2
          (horig j)).trans
            ((le_sign_value_on K A c q k i
              (le_sign_of_not_ge K A c q k i hi) W hW y).trans
                (ge_sign_value_on K A c q k owner howner W hW y))
      · rw [localUnitFamilyOn, if_neg hj, localUnitFamilyOn, if_pos howner,
          BerkovichSpectrumOver.map_one]
        exact ge_sign_value_on K A c q k owner howner W hW y

private noncomputable def localRefinementRebasedRestrictedGeneratedOn {r : ℕ}
    {c : K} (hc : 0 < ‖c‖) (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier) :
    Refinement K W.Sections
      (localGeneratedCoverOn K A (norm_pos_iff.mp hc) q hq k W)
      (rebasedRestrictedGeneratedCoverOn K A q hq W) where
  index i := geIndex K A c q hr hlarge k i
  subset i y hy := by
    classical
    change Fin r at i
    have hlocal :
        ∀ j, y (localUnitFamilyOn K A c q k W j) ≤
          y (localUnitFamilyOn K A c q k W i) := by
      change y ∈ (generatedDomain K W.Sections
        (localUnitFamilyOn K A c q k W)
        (localUnitFamilyOn_span_top K A (norm_pos_iff.mp hc) q hq k W)
        i).carrier at hy
      exact (mem_generatedDomain_carrier K W.Sections
        (localUnitFamilyOn K A c q k W)
        (localUnitFamilyOn_span_top K A (norm_pos_iff.mp hc) q hq k W)
        i y).1 hy
    apply
      (mem_rebasedRestrictedGeneratedCoverOn_domain_iff K A q hq W
        (geIndex K A c q hr hlarge k i) y).2
    intro j
    by_cases hi : IsGESign K A c q k i
    · simp only [geIndex, hi, if_pos]
      apply (subdomainBaseMap_scaled_le_iff K A hc q W j i y).1
      by_cases hj : IsGESign K A c q k j
      · simpa only [localUnitFamilyOn, if_pos hj, if_pos hi] using hlocal j
      · exact (le_sign_value_on K A c q k j
          (le_sign_of_not_ge K A c q k j hj) W hW y).trans
            (ge_sign_value_on K A c q k i hi W hW y)
    · let owner := geOwner K A c q hr hlarge k
      have hindex : geIndex K A c q hr hlarge k i = owner := by
        simp [geIndex, hi, owner]
      rw [hindex]
      have howner : IsGESign K A c q k owner :=
        geOwner_spec K A c q hr hlarge k
      apply (subdomainBaseMap_scaled_le_iff K A hc q W j owner y).1
      by_cases hj : IsGESign K A c q k j
      · have hjone :
            y (subdomainBaseMap K A W (scaledFamily K A c q j)) ≤ 1 := by
          simpa only [localUnitFamilyOn, if_pos hj, if_neg hi,
            BerkovichSpectrumOver.map_one] using hlocal j
        exact hjone.trans (ge_sign_value_on K A c q k owner howner W hW y)
      · exact (le_sign_value_on K A c q k j
          (le_sign_of_not_ge K A c q k j hj) W hW y).trans
            (ge_sign_value_on K A c q k owner howner W hW y)

/-- The generated cover remains acyclic after restriction to every rational
subdomain contained in one chart of the scaled Laurent cover. -/
private theorem restrictTo_generated_inside_chart_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) {r : ℕ} {c : K} (hc : 0 < ‖c‖)
    (q : Fin r → A) (hq : Ideal.span (Set.range q) = ⊤)
    (hr : Nonempty (Fin r))
    (hlarge : ∀ x : BerkovichSpectrumOver K A,
      ∃ i : Fin r, 1 < x (scaledFamily K A c q i))
    (k : Fin (scaledLaurentCover K A c q).m)
    (W : AffinoidRationalSubdomain K A)
    (hW : W.carrier ⊆ ((scaledLaurentCover K A c q).domain k).carrier) :
    (((generated K A q hq).restrictTo K A W (by
      simpa only [carrier_whole] using Set.subset_univ W.carrier)
        ).normalizedCechComplex K A hA).Acyclic := by
  rw [normalizedCechComplex_acyclic_iff_rebase K A hA]
  exact
    (normalizedCechComplex_acyclic_iff_of_mutual_refinement K W.Sections
      (isAffinoidAlgebra_sections K A hA W)
      (rebasedRestrictedGeneratedCoverOn K A q hq W)
      (localGeneratedCoverOn K A (norm_pos_iff.mp hc) q hq k W)
      (localRefinementRebasedRestrictedGeneratedOn
        K A hc q hq hr hlarge k W hW)
      (rebasedRestrictedGeneratedOnRefinementLocal
        K A hc q hq hr hlarge k W hW)).2
      (unitGenerated_normalizedCechComplex_acyclic K W.Sections
        (isAffinoidAlgebra_sections K A hA W)
        (localUnitFamilyOn K A c q k W)
        (localUnitFamilyOn_span_top K A (norm_pos_iff.mp hc) q hq k W)
        hr (localUnitFamilyOn_isUnit K A c q k W hW))

/-- A rational cover generated by a finite family spanning the unit ideal is
Čech-acyclic.  The proof is the scaled-Laurent reduction of BGR 8.2.2,
Lemma 3, combined with the double-Čech comparison theorem. -/
theorem generated_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r)) :
    ((generated K A q hq).normalizedCechComplex K A hA).Acyclic := by
  obtain ⟨c, hc, hlarge⟩ := exists_scalingConstant K A q hq hr
  apply normalizedCechComplex_acyclic_of_double K A hA
    (generated K A q hq) (scaledLaurentCover K A c q)
    (laurentProduct_normalizedCechComplex_acyclic K A hA
      1 (scaledFamilyList K A c q))
  · intro p
    have hvertical :
        (Cech.Presheaf.Family.verticalAugmentedCofaceModule
          ((scaledLaurentCover K A c q).cechFamily K A hA)
          ((generated K A q hq).cechFamily K A hA) p).complex.Acyclic := by
      apply verticalAugmentedCofaceModule_acyclic_of_restrictTo
        K A hA (scaledLaurentCover K A c q) (generated K A q hq) p
      intro σ
      exact
        restrictTo_generated_inside_chart_normalizedCechComplex_acyclic
          K A hA hc q hq hr hlarge (σ 0)
          (((scaledLaurentCover K A c q).cechFamily K A hA).tupleInter p σ)
          (((scaledLaurentCover K A c q).cechFamily K A hA
            ).tupleInter_subset_domain p σ 0)
    intro n
    exact (hvertical n).of_iso
      (Cech.Presheaf.Family.verticalAugmentedCofaceModuleIso
        ((scaledLaurentCover K A c q).cechFamily K A hA)
        ((generated K A q hq).cechFamily K A hA) p)
  · intro p
    apply verticalAugmentedCofaceModule_acyclic_of_restrictTo
      K A hA (generated K A q hq) (scaledLaurentCover K A c q) p
    intro σ
    exact restrictTo_laurentProduct_normalizedCechComplex_acyclic K A hA
      (((generated K A q hq).cechFamily K A hA).tupleInter p σ)
      1 (scaledFamilyList K A c q)

end AffinoidRationalSubdomain.Cover

end Rigid
