import Rigid.AffinoidSpectrum.CoverProduct
import Rigid.AffinoidSpectrum.LaurentRestriction

set_option linter.style.header false

/-!
# Finite Laurent product covers

A Laurent cover generated by finitely many functions is the iterated product of their
two-member Laurent covers.  BGR 8.2.3 reduces its acyclicity to the one-function case using
product-cover comparison.  This file carries out that induction.
-/

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

namespace AffinoidRationalSubdomain.Cover

/-- The Laurent cover generated by `f` followed by the functions in `fs`. -/
noncomputable def laurentProduct (f : A) :
    List A → Cover K A (whole K A)
  | [] => laurent K A f
  | g :: gs => product K A (laurentProduct f gs) (laurent K A g)

/-- Every finite nonempty Laurent product cover is acyclic. -/
theorem laurentProduct_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) (f : A) :
    ∀ fs : List A,
      (laurentProduct K A f fs).normalizedCechComplex K A hA |>.Acyclic
  | [] => laurent_normalizedCechComplex_acyclic K A hA f
  | g :: gs => by
      apply
        (product_normalizedCechComplex_acyclic_iff_left K A hA
          (laurentProduct K A f gs) (laurent K A g) ?_).2
      · exact laurentProduct_normalizedCechComplex_acyclic hA f gs
      · intro p σ
        exact restrictTo_laurent_normalizedCechComplex_acyclic K A hA
          ((laurentProduct K A f gs).cechFamily K A hA |>.tupleInter p σ) g

/-- A chart of a finite Laurent product makes one fixed choice of sign for every
generating function. -/
theorem laurentProduct_domain_sign_of_mem (f : A) :
    ∀ (fs : List A) (g : A), g = f ∨ g ∈ fs →
      ∀ i : Fin (laurentProduct K A f fs).m,
        (∀ x ∈ ((laurentProduct K A f fs).domain i).carrier, x g ≤ 1) ∨
          (∀ x ∈ ((laurentProduct K A f fs).domain i).carrier, 1 ≤ x g)
  | [], g, hg, i => by
      have hgf : g = f := hg.resolve_right (by simp)
      subst g
      change Fin 2 at i
      fin_cases i
      · left
        intro x hx
        exact (mem_carrier_laurentLE K A f x).1 hx
      · right
        intro x hx
        exact (mem_carrier_laurentGE K A f x).1 hx
  | g₀ :: gs, g, hg, i => by
      let 𝒰 := laurentProduct K A f gs
      let 𝒱 := laurent K A g₀
      let ij := productPair K A 𝒰 𝒱 i
      rcases hg with hgf | hglist
      · obtain hsign :=
          laurentProduct_domain_sign_of_mem f gs g (Or.inl hgf) ij.1
        exact hsign.imp
          (fun h x hx ↦ h x (inter_subset_left K A _ _ hx))
          (fun h x hx ↦ h x (inter_subset_left K A _ _ hx))
      · rcases List.mem_cons.mp hglist with hg₀ | hgs
        · rw [hg₀]
          have hright :
              (∀ x ∈ (𝒱.domain ij.2).carrier, x g₀ ≤ 1) ∨
                (∀ x ∈ (𝒱.domain ij.2).carrier, 1 ≤ x g₀) := by
            refine Fin.cases ?_ (fun j ↦ ?_) ij.2
            · left
              intro x hx
              exact (mem_carrier_laurentLE K A g₀ x).1 hx
            · have hj : j = 0 := Fin.eq_zero j
              subst j
              right
              intro x hx
              exact (mem_carrier_laurentGE K A g₀ x).1 hx
          exact hright.imp
            (fun h x hx ↦ h x (inter_subset_right K A _ _ hx))
            (fun h x hx ↦ h x (inter_subset_right K A _ _ hx))
        · obtain hsign :=
            laurentProduct_domain_sign_of_mem f gs g (Or.inr hgs) ij.1
          exact hsign.imp
            (fun h x hx ↦ h x (inter_subset_left K A _ _ hx))
            (fun h x hx ↦ h x (inter_subset_left K A _ _ hx))

private noncomputable abbrev mapToSections
    (W : AffinoidRationalSubdomain K A) (f : A) : W.Sections :=
  RationalLocalization.baseMap K A W.n W.g W.f f

private noncomputable def mappedLaurentProduct
    (W : AffinoidRationalSubdomain K A) (f : A) :
    List A → Cover K W.Sections (whole K W.Sections)
  | [] => laurent K W.Sections (mapToSections K A W f)
  | g :: gs =>
      product K W.Sections (mappedLaurentProduct W f gs)
        (laurent K W.Sections (mapToSections K A W g))

/-- The recursively induced identification of the chart indices before and after applying
the restriction map. -/
private noncomputable def mappedLaurentProductIndexEquiv
    (W : AffinoidRationalSubdomain K A) (f : A) :
    ∀ fs : List A,
      Fin (laurentProduct K A f fs).m ≃ Fin (mappedLaurentProduct K A W f fs).m
  | [] => Equiv.refl _
  | g :: gs => by
      let 𝒰 := laurentProduct K A f gs
      let 𝒱 := laurent K A g
      let 𝒰' := mappedLaurentProduct K A W f gs
      let 𝒱' := laurent K W.Sections (mapToSections K A W g)
      let e := mappedLaurentProductIndexEquiv W f gs
      exact
        { toFun := fun i ↦
            productIndex K W.Sections 𝒰' 𝒱'
              (e (productPair K A 𝒰 𝒱 i).1, (productPair K A 𝒰 𝒱 i).2)
          invFun := fun i ↦
            productIndex K A 𝒰 𝒱
              (e.symm (productPair K W.Sections 𝒰' 𝒱' i).1,
                (productPair K W.Sections 𝒰' 𝒱' i).2)
          left_inv := by
            intro i
            simp only [productPair_productIndex, Equiv.symm_apply_apply]
            exact productIndex_productPair K A 𝒰 𝒱 i
          right_inv := by
            intro i
            simp only [productPair_productIndex, Equiv.apply_symm_apply]
            exact productIndex_productPair K W.Sections 𝒰' 𝒱' i }

@[simp]
private theorem mappedLaurentProductIndexEquiv_cons_productIndex
    (W : AffinoidRationalSubdomain K A) (f g : A) (gs : List A)
    (ij : ProductIndex K A (laurentProduct K A f gs) (laurent K A g)) :
    mappedLaurentProductIndexEquiv K A W f (g :: gs)
        (productIndex K A (laurentProduct K A f gs) (laurent K A g) ij) =
      productIndex K W.Sections
        (mappedLaurentProduct K A W f gs)
        (laurent K W.Sections (mapToSections K A W g))
        (mappedLaurentProductIndexEquiv K A W f gs ij.1, ij.2) := by
  change
    productIndex K W.Sections
        (mappedLaurentProduct K A W f gs)
        (laurent K W.Sections (mapToSections K A W g))
        (mappedLaurentProductIndexEquiv K A W f gs
            (productPair K A (laurentProduct K A f gs) (laurent K A g)
              (productIndex K A (laurentProduct K A f gs) (laurent K A g) ij)).1,
          (productPair K A (laurentProduct K A f gs) (laurent K A g)
            (productIndex K A (laurentProduct K A f gs) (laurent K A g) ij)).2) =
      _
  rw [productPair_productIndex]

/-- The finite Laurent product after applying the restriction map is acyclic.  This
definition follows the original list, rather than the mapped list, so its chart index
type is definitionally the same as that of the original Laurent product. -/
private theorem mappedLaurentProduct_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A)
    (W : AffinoidRationalSubdomain K A) (f : A) :
    ∀ fs : List A,
      (mappedLaurentProduct K A W f fs).normalizedCechComplex K W.Sections
        (isAffinoidAlgebra_sections K A hA W) |>.Acyclic
  | [] =>
      laurent_normalizedCechComplex_acyclic K W.Sections
        (isAffinoidAlgebra_sections K A hA W) (mapToSections K A W f)
  | g :: gs => by
      apply
        (product_normalizedCechComplex_acyclic_iff_left K W.Sections
          (isAffinoidAlgebra_sections K A hA W)
          (mappedLaurentProduct K A W f gs)
          (laurent K W.Sections (mapToSections K A W g)) ?_).2
      · exact mappedLaurentProduct_normalizedCechComplex_acyclic hA W f gs
      · intro p σ
        exact restrictTo_laurent_normalizedCechComplex_acyclic K W.Sections
          (isAffinoidAlgebra_sections K A hA W)
          ((mappedLaurentProduct K A W f gs).cechFamily K W.Sections
            (isAffinoidAlgebra_sections K A hA W) |>.tupleInter p σ)
          (mapToSections K A W g)

/-- Restricting and rebasing a finite Laurent product gives the same chart carriers as the
finite Laurent product of the restricted functions. -/
theorem rebase_restrictTo_laurentProduct_domain_carrier_eq
    (W : AffinoidRationalSubdomain K A) (f : A) :
    ∀ (fs : List A)
      (i : Fin (laurentProduct K A f fs).m),
      (((laurentProduct K A f fs).restrictTo K A W (by
        simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A
          |>.domain i).carrier =
        (mappedLaurentProduct K A W f fs
          |>.domain (mappedLaurentProductIndexEquiv K A W f fs i)).carrier
  | [], i => rebase_restrictTo_laurent_domain_carrier_eq K A W f i
  | g :: gs, i => by
      let 𝒰 := laurentProduct K A f gs
      let 𝒱 := laurent K A g
      let ij := productPair K A 𝒰 𝒱 i
      let e := mappedLaurentProductIndexEquiv K A W f gs
      have htail :=
        rebase_restrictTo_laurentProduct_domain_carrier_eq W f gs ij.1
      have hg :=
        rebase_restrictTo_laurent_domain_carrier_eq K A W g ij.2
      have hi : productIndex K A 𝒰 𝒱 ij = i :=
        productIndex_productPair K A 𝒰 𝒱 i
      rw [← hi]
      rw [mappedLaurentProductIndexEquiv_cons_productIndex]
      ext y
      dsimp only [laurentProduct, mappedLaurentProduct]
      have hp :
          productPair K A (laurentProduct K A f gs) (laurent K A g)
              (productIndex K A 𝒰 𝒱 ij) = ij := by
        simpa only [𝒰, 𝒱] using productPair_productIndex K A 𝒰 𝒱 ij
      rw [hp]
      have hp' :
          productPair K W.Sections
              (mappedLaurentProduct K A W f gs)
              (laurent K W.Sections (mapToSections K A W g))
              (productIndex K W.Sections
                (mappedLaurentProduct K A W f gs)
                (laurent K W.Sections (mapToSections K A W g))
                (e ij.1, ij.2)) =
            (e ij.1, ij.2) :=
        productPair_productIndex K W.Sections
          (mappedLaurentProduct K A W f gs)
          (laurent K W.Sections (mapToSections K A W g)) _
      rw [hp']
      have htail_y := Set.ext_iff.mp htail y
      have hg_y := Set.ext_iff.mp hg y
      rw [mem_rebase_carrier_iff, carrier_inter, Set.mem_inter_iff] at htail_y hg_y
      rw [mem_rebase_carrier_iff]
      simp only [carrier_inter, Set.mem_inter_iff]
      constructor
      · rintro ⟨hyW, hy𝒰, hy𝒱⟩
        exact ⟨htail_y.1 ⟨hyW, hy𝒰⟩, hg_y.1 ⟨hyW, hy𝒱⟩⟩
      · rintro ⟨hy𝒰, hy𝒱⟩
        have hyW := ambientPoint_mem_carrier K A W y
        exact ⟨hyW, (htail_y.2 hy𝒰).2, (hg_y.2 hy𝒱).2⟩

private noncomputable def rebaseRestrictLaurentProductRefinement
    (W : AffinoidRationalSubdomain K A) (f : A) (fs : List A) :
    Refinement K W.Sections
      (((laurentProduct K A f fs).restrictTo K A W (by
          simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A)
      (mappedLaurentProduct K A W f fs) where
  index := mappedLaurentProductIndexEquiv K A W f fs
  subset i :=
    (rebase_restrictTo_laurentProduct_domain_carrier_eq K A W f fs i).le

private noncomputable def laurentProductRefinementRebaseRestrict
    (W : AffinoidRationalSubdomain K A) (f : A) (fs : List A) :
    Refinement K W.Sections
      (mappedLaurentProduct K A W f fs)
      (((laurentProduct K A f fs).restrictTo K A W (by
          simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A) where
  index := (mappedLaurentProductIndexEquiv K A W f fs).symm
  subset i := by
    simpa only [Equiv.apply_symm_apply] using
      (rebase_restrictTo_laurentProduct_domain_carrier_eq K A W f fs
        ((mappedLaurentProductIndexEquiv K A W f fs).symm i)).ge

/-- Every finite Laurent product cover remains acyclic after restriction to a rational
subdomain. -/
theorem restrictTo_laurentProduct_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A)
    (W : AffinoidRationalSubdomain K A) (f : A) (fs : List A) :
    (((laurentProduct K A f fs).restrictTo K A W (by
      simpa only [carrier_whole] using Set.subset_univ W.carrier)
        ).normalizedCechComplex K A hA).Acyclic := by
  rw [normalizedCechComplex_acyclic_iff_rebase K A hA]
  exact
    (normalizedCechComplex_acyclic_iff_of_mutual_refinement K W.Sections
      (isAffinoidAlgebra_sections K A hA W)
      (((laurentProduct K A f fs).restrictTo K A W (by
          simpa only [carrier_whole] using Set.subset_univ W.carrier)).rebase K A)
      (mappedLaurentProduct K A W f fs)
      (laurentProductRefinementRebaseRestrict K A W f fs)
      (rebaseRestrictLaurentProductRefinement K A W f fs)).2
        (mappedLaurentProduct_normalizedCechComplex_acyclic K A hA W f fs)

end AffinoidRationalSubdomain.Cover

end Rigid
