import Rigid.AffinoidSpectrum.LaurentProduct
import Rigid.Berkovich.Unit

set_option linter.style.header false

/-!
# Rational covers generated by units

BGR 8.2.2, Lemma 4 refines a rational cover generated by units by a Laurent
cover.  We use all ordered ratios `qᵢ / qⱼ`; a chart fixes one inequality for
each ratio, hence induces a total preorder on the finite set of generators.
A maximal generator owns the chart.
-/

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (A : Type v) [NormedCommRing A] [NormedAlgebra K A] [CompleteSpace A]
  [IsUltrametricDist A]

namespace AffinoidRationalSubdomain.Cover

/-- The quotient `qᵢ / qⱼ`, using the specified unit structure on `qⱼ`. -/
private noncomputable def unitRatio {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) (i j : Fin r) : A :=
  q i * ↑((hunit j).unit⁻¹)

private theorem apply_unitRatio {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) (i j : Fin r)
    (x : BerkovichSpectrumOver K A) :
    x (unitRatio A q hunit i j) = x (q i) * (x (q j))⁻¹ := by
  rw [unitRatio, BerkovichSpectrumOver.map_mul]
  congr 1
  have hmul : x (q j) * x (↑((hunit j).unit⁻¹) : A) = 1 := by
    rw [← BerkovichSpectrumOver.map_mul]
    have hring : q j * (↑((hunit j).unit⁻¹) : A) = 1 := by
      calc
        q j * (↑((hunit j).unit⁻¹) : A) =
            (↑(hunit j).unit : A) * ↑((hunit j).unit⁻¹) :=
          congrArg (fun a : A ↦ a * ↑((hunit j).unit⁻¹))
            (hunit j).unit_spec.symm
        _ = 1 := (hunit j).mul_val_inv
    rw [hring, BerkovichSpectrumOver.map_one]
  exact (inv_eq_of_mul_eq_one_right hmul).symm

private theorem unitRatio_le_one_iff {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) (i j : Fin r)
    (x : BerkovichSpectrumOver K A) :
    x (unitRatio A q hunit i j) ≤ 1 ↔ x (q i) ≤ x (q j) := by
  rw [apply_unitRatio K A q hunit i j x]
  have hne := BerkovichSpectrumOver.apply_ne_zero_of_isUnit K A (hunit j) x
  have hpos : 0 < x (q j) :=
    lt_of_le_of_ne (BerkovichSpectrumOver.nonneg K A x (q j)) hne.symm
  rw [mul_inv_le_iff₀ hpos, one_mul]

private theorem one_le_unitRatio_iff {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) (i j : Fin r)
    (x : BerkovichSpectrumOver K A) :
    1 ≤ x (unitRatio A q hunit i j) ↔ x (q j) ≤ x (q i) := by
  rw [apply_unitRatio K A q hunit i j x]
  have hne := BerkovichSpectrumOver.apply_ne_zero_of_isUnit K A (hunit j) x
  have hpos : 0 < x (q j) :=
    lt_of_le_of_ne (BerkovichSpectrumOver.nonneg K A x (q j)) hne.symm
  rw [le_mul_inv_iff₀ hpos, one_mul]

/-- Enumerate all ordered ratios of a finite unit family. -/
private noncomputable def unitRatioList {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) : List A :=
  List.ofFn fun k : Fin (r * r) ↦
    let ij : Fin r × Fin r := finProdFinEquiv.symm k
    unitRatio A q hunit ij.1 ij.2

private theorem unitRatio_mem_unitRatioList {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) (i j : Fin r) :
    unitRatio A q hunit i j ∈ unitRatioList A q hunit := by
  rw [unitRatioList, List.mem_ofFn']
  refine ⟨finProdFinEquiv (i, j), ?_⟩
  simp

/-- The Laurent product generated by all ordered ratios of a unit family. -/
noncomputable def unitGeneratedLaurentCover {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i)) : Cover K A (whole K A) :=
  laurentProduct K A 1 (unitRatioList A q hunit)

private theorem unitGeneratedLaurentCover_pair_total {r : ℕ} (q : Fin r → A)
    (hunit : ∀ i, IsUnit (q i))
    (k : Fin (unitGeneratedLaurentCover K A q hunit).m) (i j : Fin r) :
    (∀ x ∈ ((unitGeneratedLaurentCover K A q hunit).domain k).carrier,
        x (q i) ≤ x (q j)) ∨
      (∀ x ∈ ((unitGeneratedLaurentCover K A q hunit).domain k).carrier,
        x (q j) ≤ x (q i)) := by
  obtain hsign :=
    laurentProduct_domain_sign_of_mem K A 1
      (unitRatioList A q hunit) (unitRatio A q hunit i j)
      (Or.inr (unitRatio_mem_unitRatioList A q hunit i j)) k
  exact hsign.imp
    (fun h x hx ↦ (unitRatio_le_one_iff K A q hunit i j x).1 (h x hx))
    (fun h x hx ↦ (one_le_unitRatio_iff K A q hunit i j x).1 (h x hx))

private theorem unitGeneratedLaurentCover_exists_owner {r : ℕ} (q : Fin r → A)
    (hr : Nonempty (Fin r)) (hunit : ∀ i, IsUnit (q i))
    (k : Fin (unitGeneratedLaurentCover K A q hunit).m) :
    ∃ owner : Fin r,
      ∀ j x, x ∈ ((unitGeneratedLaurentCover K A q hunit).domain k).carrier →
        x (q j) ≤ x (q owner) := by
  let R (i j : Fin r) : Prop :=
    ∀ x, x ∈ ((unitGeneratedLaurentCover K A q hunit).domain k).carrier →
      x (q i) ≤ x (q j)
  letI : LE (Fin r) := ⟨R⟩
  letI : IsTrans (Fin r) (· ≤ ·) :=
    ⟨fun _ _ _ hij hjl x hx ↦ (hij x hx).trans (hjl x hx)⟩
  letI : Nonempty (Fin r) := hr
  have htotal (i j : Fin r) : i ≤ j ∨ j ≤ i := by
    change R i j ∨ R j i
    exact
      unitGeneratedLaurentCover_pair_total K A q hunit k i j
  letI : Std.Total (fun i j : Fin r ↦ i ≤ j) := ⟨htotal⟩
  obtain ⟨owner, hmax⟩ :=
    (Set.toFinite (Set.univ : Set (Fin r))).exists_maximal Set.univ_nonempty
  refine ⟨owner, fun j ↦ ?_⟩
  change R j owner
  rcases htotal owner j with h | h
  · exact hmax.2 (Set.mem_univ j) h
  · exact h

/-- BGR 8.2.2, Lemma 4: a Laurent cover refines a rational cover generated
by units. -/
noncomputable def unitGeneratedLaurentRefinement {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hunit : ∀ i, IsUnit (q i)) :
    Refinement K A (unitGeneratedLaurentCover K A q hunit) (generated K A q hq) where
  index k := Classical.choose
    (unitGeneratedLaurentCover_exists_owner K A q hr hunit k)
  subset k x hx :=
    (mem_generatedDomain_carrier K A q hq _ x).2 fun j ↦
      Classical.choose_spec
        (unitGeneratedLaurentCover_exists_owner K A q hr hunit k) j x hx

/-- A rational cover generated by a finite unit family is Čech-acyclic. -/
theorem unitGenerated_normalizedCechComplex_acyclic
    (hA : IsAffinoidAlgebra K A) {r : ℕ} (q : Fin r → A)
    (hq : Ideal.span (Set.range q) = ⊤) (hr : Nonempty (Fin r))
    (hunit : ∀ i, IsUnit (q i)) :
    ((generated K A q hq).normalizedCechComplex K A hA).Acyclic := by
  refine
    (normalizedCechComplex_acyclic_iff_of_refinement K A hA
      (generated K A q hq) (unitGeneratedLaurentCover K A q hunit)
      (unitGeneratedLaurentRefinement K A q hq hr hunit) ?_).2 ?_
  · intro p σ
    exact restrictTo_laurentProduct_normalizedCechComplex_acyclic K A hA
      ((generated K A q hq).cechFamily K A hA |>.tupleInter p σ)
      1 (unitRatioList A q hunit)
  · exact
      laurentProduct_normalizedCechComplex_acyclic K A hA
        1 (unitRatioList A q hunit)

end AffinoidRationalSubdomain.Cover

end Rigid
